spring:
  datasource:
    url: ${APPL_DATASOURCE_JDBC_URL}
    username: ${APPL_DATASOURCE_USERNAME}
    password: ${APPL_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${APPL_DATASOURCE_JDBC_URL}
    user: ${APPL_DATASOURCE_USERNAME}
    password: ${APPL_DATASOURCE_PASSWORD}
